/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Question {
  'id' : string,
  'marks' : bigint,
  'content' : string,
  'difficulty' : string,
  'correctAnswer' : string,
  'questionType' : QuestionType,
  'image' : [] | [ExternalBlob],
  'chapter' : bigint,
  'options' : [] | [Array<string>],
}
export type QuestionType = { 'mcq' : null } |
  { 'shortAnswer' : null } |
  { 'longAnswer' : null } |
  { 'imageBased' : null };
export interface QuestionUpdateArgs {
  'marks' : bigint,
  'content' : string,
  'difficulty' : string,
  'correctAnswer' : string,
  'questionType' : QuestionType,
  'image' : [] | [ExternalBlob],
  'chapter' : bigint,
  'options' : [] | [Array<string>],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addQuestion' : ActorMethod<[QuestionUpdateArgs], string>,
  'deleteQuestion' : ActorMethod<[string], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getQuestionById' : ActorMethod<[string], Question>,
  'getQuestionsByChapter' : ActorMethod<[bigint], Array<Question>>,
  'getQuestionsByChapterAndType' : ActorMethod<
    [bigint, QuestionType],
    Array<Question>
  >,
  'getQuestionsByType' : ActorMethod<[QuestionType], Array<Question>>,
  'updateQuestion' : ActorMethod<[string, QuestionUpdateArgs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];