/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const QuestionType = IDL.Variant({
  'mcq' : IDL.Null,
  'shortAnswer' : IDL.Null,
  'longAnswer' : IDL.Null,
  'imageBased' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const QuestionUpdateArgs = IDL.Record({
  'marks' : IDL.Nat,
  'content' : IDL.Text,
  'difficulty' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'image' : IDL.Opt(ExternalBlob),
  'chapter' : IDL.Nat,
  'options' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'marks' : IDL.Nat,
  'content' : IDL.Text,
  'difficulty' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'image' : IDL.Opt(ExternalBlob),
  'chapter' : IDL.Nat,
  'options' : IDL.Opt(IDL.Vec(IDL.Text)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addQuestion' : IDL.Func([QuestionUpdateArgs], [IDL.Text], []),
  'deleteQuestion' : IDL.Func([IDL.Text], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestionById' : IDL.Func([IDL.Text], [Question], ['query']),
  'getQuestionsByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getQuestionsByChapterAndType' : IDL.Func(
      [IDL.Nat, QuestionType],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getQuestionsByType' : IDL.Func(
      [QuestionType],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'updateQuestion' : IDL.Func([IDL.Text, QuestionUpdateArgs], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const QuestionType = IDL.Variant({
    'mcq' : IDL.Null,
    'shortAnswer' : IDL.Null,
    'longAnswer' : IDL.Null,
    'imageBased' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const QuestionUpdateArgs = IDL.Record({
    'marks' : IDL.Nat,
    'content' : IDL.Text,
    'difficulty' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'image' : IDL.Opt(ExternalBlob),
    'chapter' : IDL.Nat,
    'options' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'marks' : IDL.Nat,
    'content' : IDL.Text,
    'difficulty' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'image' : IDL.Opt(ExternalBlob),
    'chapter' : IDL.Nat,
    'options' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addQuestion' : IDL.Func([QuestionUpdateArgs], [IDL.Text], []),
    'deleteQuestion' : IDL.Func([IDL.Text], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestionById' : IDL.Func([IDL.Text], [Question], ['query']),
    'getQuestionsByChapter' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByChapterAndType' : IDL.Func(
        [IDL.Nat, QuestionType],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getQuestionsByType' : IDL.Func(
        [QuestionType],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'updateQuestion' : IDL.Func([IDL.Text, QuestionUpdateArgs], [], []),
  });
};

export const init = ({ IDL }) => { return []; };